### ISSUE TITLE
Table的colNames和cols不能正常执行，'Table' object has no attribute '_Table__columns'.

### ISSUE THREAD

**Issue by tomqyp** [dolphindb/api-python#1]
`df = SomePandasDataFrame()`
`s.table(data=df)`
`df.cols`
`df.colNames`
>>>AttributeError: 'Table' object has no attribute '_Table__columns'.
看了看代码，是否忘了在Table.__init__ 中初始化__columns?

**Comment by xiaodanzhang** [comment]
fixed
